### ISSUE TITLE
The application only works with Internal Authentication on Opsmanager , and not with Saml Authentication

### ISSUE THREAD

**Issue by jointcloudfoundry** [pivotal-gss/tanzu-certificate-exporter#4]
Hello , we are using this application for a while , but after migratio from Internal Authentication to Saml authentication on Opsmanager , the application doesn't work anymore , because usage of user/passwrd is not allowed anymore .
Do you expect to make feasible usage of client/secret in addition to user/password in a future release ?
Thanks in advance
Best regards .

Eric

**Comment by faisaltheparttimecoder** [comment]
Hey Eric,

Thanks for reporting the issue, based on `OM CLI` they use UAA client to extract the information when SAML is enabled, i guess this can be implemented here as well, let me check on it.

Thanks
Faisal

**Comment by faisaltheparttimecoder** [comment]
Thanks Eric, this is now fixed https://github.com/pivotal-gss/tanzu-certificate-exporter/pull/5

for SAML enabled env, you have to create a client like this 

ref: [install doc](https://github.com/pivotal-gss/tanzu-certificate-exporter/blob/master/Install.md)

```
# If you are using SAML to authenticate user on opsmanager, then you need to setup a UAAC read only client instead of a read only user mentioned above
uaac client add prometheus-cert-exporter -s prometheus-cert-exporter-secret --scope opsman.restricted_view --authorized_grant_types client_credentials --authorities opsman.restricted_view
```

and update the manifest over [here](https://github.com/pivotal-gss/tanzu-certificate-exporter/blob/master/manifest.yml#L16-L17)

Please note to set the username and password blank when the client id and client secret is set

Thanks again, Have a lovely new year :)
